CarParts/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :cars do
    collection do
      get 'search'
    end
  end

  resources :products do
    collection do
      get 'search'
    end
  end

  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

CarParts/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CarParts/app/models/car.rb
class Car < ApplicationRecord #FIXME: doesn't like the syntax ::Base
  has_and_belongs_to_many :products #FIXED: Need to associate the car with the product.
  validates :vin, numericality: {greater_than_or_equal_to: 1}#FIXED: validations are the cause of the Failures during rails test, CarsControllerTest#test_should_create_car
  validates :make, presence:true
  validates :model, presence:true
  #validates :year, presence:true #FIXME: "Car.count" didn't change by 1. Expected: 3 Actual: 2
  validates :country, presence:true
end

CarParts/app/models/cars_product.rb
class CarsProduct < ApplicationRecord
  belongs_to :car
  belongs_to :product
end

CarParts/app/models/product.rb
class Product < ApplicationRecord #FIXME: doesn't like the syntax ::Base
  has_and_belongs_to_many :cars  #FIXED: Need to associate product with the car.
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_orequal_to: 0.01}
  validates :title, uniqueness: true #FIXME: validations are the cause of the Failures during rails test -->  Failure: ProductsControllerTest#test_should_update_product [/Users/matthewhurt/work/assignment-two-KnifeHand/CarParts/test/controllers/products_controller_test.rb:44]:
end

CarParts/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

CarParts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
end

CarParts/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
    @products = Product.all
  end

  # GET /cars/1/edit
  def edit
    @products = Product.all
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def search
    @cars = Car.where("vin like?", "%#{params[:query]}%")
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :vin, :country, :product_ids => [])
    end
end

CarParts/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @cars = Car.all
  end

  # GET /products/1/edit
  def edit
    @cars = Car.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @product = Products.where("part like?", "%#{params[:query]}%")
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :car_ids => [])
    end
end

CarParts/app/helpers/application_helper.rb
module ApplicationHelper
end

CarParts/app/helpers/cars_helper.rb
module CarsHelper
end

CarParts/app/helpers/products_helper.rb
module ProductsHelper
end

CarParts/app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make %>
    <!--%= f.collection_check_boxes(_ids, @car) %-->
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :vin %>
    <%= form.text_field :vin %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <<div class="field">
    <%= form.label :car_Products %><br>
    <%= form.collection_check_boxes(:product_ids, @products, :id, :title) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

CarParts/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

CarParts/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<%= form_tag(search_cars_url, method: "get") do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
  <% end %>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Vin</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.vin %></td>
        <td><%= car.country %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>
<p>
 <a href="/products">Checkout the products page</a>!
</p>

CarParts/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

CarParts/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Country:</strong>
  <%= @car.country %>
</p>

<!--strong>Products:</strong--> <!-- FIXME: Breaks the page -->
<!-- ul-->
  <!-- % @car.products.each do |product| % -->
  <!-- li>< %= products.products %></li -->
  <!-- % end % -->
<!-- /ul -->

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

CarParts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarParts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <%= yield %>
  </body>
</html>

CarParts/app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
q
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows:10, cols: 60 %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :car %>
    <%= form.text_field :car %>
    <!--f.collection_check_boxes (:library_ids, @libraries, :id, :name) %--> <!-- FIXME: Doesn't like this-->
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <div class ="field">
    <%=form.label :product_id %>
    <%= form.collection_select :product_id, Car.all, :id, :make %>
  </div>
<% end %>

CarParts/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

CarParts/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= form_tag(search_products_url, method: "get") do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
  <% end %>

  <br/><div id="results"></div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td><%= product.car %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <a href="/cars">See Cars</a>!
</p>

<br>

<%= link_to 'New Product', new_product_path %>

CarParts/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

CarParts/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Car:</strong>
  <%= @product.car %>
</p>

<!--ul-->
  <!--% @car.products.each do |car| %-->
  <!--li-->
    <!--%= car.name %-->
  <!--/li-->
  <!--% end %-->
<!--/ul-->

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>